[package]
name = "reppor"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
reqwest = { version = "0.12.4", features = ["json"] }
serde_json = "1.0.116"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.10"